# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hello < Formula
  desc "Hello
"
  homepage "https://github.com/szksh-lab/hello"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/szksh-lab/hello/releases/download/v0.1.1/hello_darwin_amd64.tar.gz"
      sha256 "5a342b8937b1a760b3c7c58ac344dbe98f2bb341ebccb79fdb2f428250393de0"

      def install
        bin.install "hello"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/szksh-lab/hello/releases/download/v0.1.1/hello_darwin_arm64.tar.gz"
      sha256 "bdab00c13b3089543f3c26b980122c6adeae31bf222cbefa6065baacceb60315"

      def install
        bin.install "hello"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/szksh-lab/hello/releases/download/v0.1.1/hello_linux_amd64.tar.gz"
        sha256 "e9d01a46c89da53b8ad7ff2dcd8a99831865914471fd4ef39beeed6c72cfb49e"

        def install
          bin.install "hello"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/szksh-lab/hello/releases/download/v0.1.1/hello_linux_arm64.tar.gz"
        sha256 "98e5e43c28575c06f788e2628e9f5b88e0989fed1729bde9292b7c52e99924e4"

        def install
          bin.install "hello"
        end
      end
    end
  end

  test do
    system "#{bin}/hello"
  end
end
