# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hello < Formula
  desc "Hello
"
  homepage "https://github.com/szksh-lab/hello"
  version "0.1.0-3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/szksh-lab/hello/releases/download/v0.1.0-3/hello_darwin_amd64.tar.gz"
      sha256 "76c4c78da5dc35cd7088d08b298dea8f2865b9956efd9f1c7c7601ec38e273a3"

      def install
        bin.install "hello"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/szksh-lab/hello/releases/download/v0.1.0-3/hello_darwin_arm64.tar.gz"
      sha256 "eb88de4ffef095d336a534253e353237b85ab2eb895ee5a3c5fb27ff47f28a46"

      def install
        bin.install "hello"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/szksh-lab/hello/releases/download/v0.1.0-3/hello_linux_amd64.tar.gz"
        sha256 "436bc6e8d7b2a80f16a8e95a9954d8aa0b6756f99cd9450abee1e8b213d44ab0"

        def install
          bin.install "hello"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/szksh-lab/hello/releases/download/v0.1.0-3/hello_linux_arm64.tar.gz"
        sha256 "6f8bbaa5d56578b0630ab172b8e6baa6220780c2ce119a350eb0bb7fcb6fb98d"

        def install
          bin.install "hello"
        end
      end
    end
  end

  test do
    system "#{bin}/hello"
  end
end
